### PR TITLE
Add Appple iOS emoji 16.4 support

### PR DESCRIPTION
**Pull request by direc85**
What it says on the tin! :)

### CODE REVIEW

**Comment by ichthyosaurus** [comment]
Thanks :) Did you update it in Whisperfish too?

Edit: ah yes you did, thanks :).

Edit 2: ok, turns out I messed up my Gitlab/Whisperfish stuff so I can't update the version number there right now. Can you please set it to 0.3.1 here: https://gitlab.com/whisperfish/whisperfish/-/blob/c8567ecfb494e785a6242f5608648f52cd132e22/qml/js/emoji.js#L50

**Comment by ichthyosaurus** [comment]
Another problem: we currently use the regex from https://github.com/twitter/twemoji/blob/64b63c21b8a1524dd4bbfa112e826e76348a7219/v/13.0.1/twemoji.js for detecting emojis, but Twemoji appears to be dead since this Musk guy bought Twitter. So we have to find another solution...

Also, Openmoji isn't ready yet for Emoji 15, so we'll have to wait until the keyboard (= sailor-emoji = Whisperfish) can actually support the new emojis: https://github.com/hfg-gmuend/openmoji/issues/410

**Comment by direc85** [comment]
Thanks, I'll bump the version!

Whisperfish uses https://github.com/twitter/twemoji-parser/blob/f8312f35fdee0e79874bb50213c4544c14fa759b/src/lib/regex.js as the source, but there's no Emoji 15 support yet either.

**Comment by direc85** [comment]
...buuuuuut there's this branch that seems to have Emoji 15 support: https://github.com/twitter/twemoji-parser/compare/master...mei23:twemoji-parser:master

And it refers to a generator script for the regex: https://github.com/twitter/twemoji-parser/blob/master/src/scala/scripts/generate.sh

**Pull request merged**
